name: synaps_generator
description: The generator used by synaps.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: '^1.0.1'
  build: '^2.0.2'
  synaps:
    path: ../

dev_dependencies:
  
